# ############################################################################
# Auido Tokenizer: Encodec
# Extraction: Google Speech Command
# Authors: Pooneh Mousavi 2024
# ############################################################################
# Seed needs to be set at top of yaml, before objects with parameters are made

seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/encodec
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/extraction_log.txt

# Data files
data_folder: !PLACEHOLDER  # e.g.,  /path/to/GSC
cached_data_folder: !ref <output_folder> # e.g., path/to/cache
train_annotation: !ref <cached_data_folder>/train.csv
valid_annotation: !ref <cached_data_folder>/valid.csv
test_annotation: !ref <cached_data_folder>/test.csv
skip_prep: False

# Use 12 for V2 12 task and 35 for V2 35 task
number_of_commands: 12
# Percentage of files used for validation and test
validation_percentage: 10
testing_percentage: 10
# Percentage of unknown and silence examples
# (relative to total of known word samples) to include
percentage_unknown: 10 # Set this to 0 for the V2 35 task
percentage_silence: 10 # Set this to 0 for the V2 35 task

batch_size: 1
num_workers: 8
src_key: wav
id_key: id

# Dataloader options
dataloader_opts:
  batch_size: !ref <batch_size>
  shuffle: True
  num_workers: !ref <num_workers>

# EnCodec parameters
# sample_rate: [24000, 24000, 24000, 24000]
# vocab_size: [1024, 1024, 1024, 1024]
# bandwidth: [1.5, 3.0, 6.0, 12.0, 24.0]
# num_codebooks: [2, 4, 8, 16, 32]
bandwidth: 24.0
num_codebooks: 32
vocab_size: 1024
sample_rate: 24000
save_embedding: False

# EnCodec model (see https://huggingface.co/docs/transformers/v4.31.0/en/model_doc/encodec)
tokenizer: !new:utils.tokenizer_interface.EncodecTokenizer
  source: facebook/encodec_24khz  # Only the 24kHz version supports mono audio
  save_path: !ref <save_folder>
  sample_rate: !ref <sample_rate>
  bandwidth: !ref <bandwidth>
  flat_embeddings: False
  freeze: True
  renorm_embeddings: False

tokens_extractor: !new:utils.tokens.TokensExtractor
  tokenizer: !ref <tokenizer>
  sample_rate: !ref <sample_rate>
  src_key: !ref <src_key>
  id_key: !ref <id_key>
  dataloader_opts: !ref <dataloader_opts>
