# ############################################################################
# Auido Tokenizer: Mimi
# Extraction: VoiceCeleb
# Authors: Pooneh Mousavi 2024
# ############################################################################
# Seed needs to be set at top of yaml, before objects with parameters are made

seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/mimi
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/extraction_log.txt

# Data files
data_folder: !PLACEHOLDER  # e.g. /path/to/Voxceleb
cached_data_folder: !ref <output_folder> # e.g., path/to/cache

verification_file: https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt #path/to/veri_test2.txt

train_annotation: !ref <cached_data_folder>/train.csv
enrol_annotation: !ref <cached_data_folder>/enrol.csv
test_annotation: !ref <cached_data_folder>/test.csv
valid_annotation: !ref  <cached_data_folder>/dev.csv
sentence_len: 3
original_sample_rate: 16000
random_chunk: True
skip_prep: False

batch_size: 1
num_workers: 8
src_key: wav
id_key: id

# Dataloader options
dataloader_opts:
  batch_size: !ref <batch_size>
  shuffle: True
  num_workers: !ref <num_workers>

####################### Model parameters ###########################
# Tokenizer parameters
model_hub: kyutai/mimi
vocab_size: 1024
num_codebooks: 32
sample_rate: 24000
# Feature parameters
encoder_dim: 1024
save_embedding: False

tokenizer: !new:utils.tokenizer_interface.MimiTokenizer
  source: !ref <model_hub>
  save_path: !ref <save_folder>
  num_codebooks: !ref <num_codebooks>
  sample_rate: !ref <sample_rate>

tokens_extractor: !new:utils.tokens.TokensExtractor
  tokenizer: !ref <tokenizer>
  sample_rate: !ref <sample_rate>
  src_key: !ref <src_key>
  id_key: !ref <id_key>
  dataloader_opts: !ref <dataloader_opts>
